# Generated by Django 5.1.4 on 2025-01-29 03:26

import task.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_remove_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktype',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=task.models.upload_tasktype_icon),
        ),
    ]
